import os
ENV = os.environ['FLASK_ENV']
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SECRET_KEY = os.environ['SECRET_KEY']
GSPREAD_API_CERT = os.environ['GSPREAD_API_CERT']
GSPREAD_TITLE = "MyCDs"