"""empty message

Revision ID: 5ba22f355e43
Revises: bd2bdb9ca0a4
Create Date: 2019-03-23 01:06:10.293945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ba22f355e43'
down_revision = 'bd2bdb9ca0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('wish_list', sa.Boolean(), nullable=True))
    op.drop_column('albums', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('albums', 'wish_list')
    # ### end Alembic commands ###
